using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Lives_System : MonoBehaviour
{
    public int The_Score = 0;
    public static int Lives = 2;
    public int Lives_Status = 2;
    public static int Stages = 1;
    public int Stage_Status = 1;
    private string[] Passwords =
       {"NMIHPPBPCAFHABDPCPCH", "HIJDIJFJDLHFLOPDJDJN", "BAJDINANMJGGCPOOLOLG", "DJOLBGLGKGJAHIEMNMNN", "NMKGDDONMHLCGKKGKGKJ", "ABGKKBPHILHFLOPCPCPC", "FEBABGLEFLHFLOPCPCPA","HIFEMIIABJGGCPOBABAN","NMEFPHCMNJGGCPOBABAF", "JDGKKBPHILHFLOPGKGKL",
        "HIPCOHCMNLHFLOPEFEFG", "ABJDIFJKGGJAHIEPCPCN", "JDBABANOLJGGCPODJDJF", "ABNMKNAIHFAJNMMKGKGF", "ABIHPGLEFCNNJDBEFEFN","JDDJOIIOLCNNJDBABOLH", "JDNMKLGHILHFLOPGKEFH", "DJABEKMPCFAJNMMOLFEL", "FEGKKJFNMAFHABDABOLN", "NMKGDDOIHJGGCPONMIHN",
        "NMKGDDOIHJGGCPONMIHN", "NMCPIIIOLFAJNMMGKEFF", "NMPCOIIOLCNNJDBBAHIJ", "NMGKKEEHILHFLOPPCGKL", "HIKGDODCPGJAHIEPCGKJ", "ABHIMGLBANCLFEINMIHH", "MNGKKDOOLGJAHIEKGCPC", "OLDJOIIKGLHFLOPEFLOL", "IHJDIKMEFNCLFEINMIHF", "IHDJOIIKGLHFLOPMNJDA",
        "DJJDIDOOLFAJNMMEFLOC","IHIHPBPCPNCBOLIHIJDH", "OLFEMANMNFADDJMABFEF", "MNDJOODJDHLPPCKBAMNA", "DJABEMKMNNCMIHIMNDJC", "BADJOIIIHAFDDJDIHOLA", "DJFEMPBPCGJKEFEEFBAC", "DJKGDIIIHJGBOLOABFEH", "DJCPIODFECNOBABABFEN","IHEFPPBGKFAIMNMOLKGJ",
        "IHLOEHCMNNCMIHIIHOLJ", "DJEFPHCMNJGBOLOABFEH", "MNGKKIIOLGJKEFEKGPCJ", "BAPCOMKDJJGBOLODJIHJ", "OLNMKDOIHFAIMNMGKLOF", "OLIHPMKNMFAIMNMABFEH", "OLABEMKNMCNOBABPCEFL","OLOLBFJGKGJKEFEFEPCL", "OLFEMFJGKLHPPCPLOMNL", "NMABEKMKGNCLFEIIHFEL"};

    // Update is called once per frame
    void Update()
    {
        // Keeps track of lives and current stage 
        Lives_Status = Lives;
        Stage_Status = Stages;
    }

    // Shows the password for the level 
    public string Stage_Password(int levels)
    {
        return Passwords[levels - 1];
    }
}
